sudo: false
language: node_js
node_js:
    - 12
    - 14

services:
    - postgresql

cache:
    directories:
        - node_modules

before_scripts:
    - psql -c 'create database travis_ci_test;' -U postgres
    - psql -d travis_ci_test -f -a ./src/sql/create_user_table.sql

install: yarn install --frozen-lockfile

script:
    - yarn run build
    - yarn run test
