sudo: false
language: node_js
node_js:
    - 12
    - 14

cache:
    directories:
        - node_modules


install: yarn install --frozen-lockfile --ignore-scripts

script:
    - npm install -g node-gyp
    - yarn run build
    - yarn run test
